name: ffi_file_io
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  ffi: ^2.1.3 # ADDED
  path: ^1.8.0 # ADDED

dev_dependencies:
  lints: ^4.0.0
